version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/*"
          - "github/*"
          - "github-community-projects/*"
      github-owned-actions:
        patterns:
          - "actions/*"
          - "github/*"
          - "github-community-projects/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
