version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/*"
          - "github/*"
      github-owned-actions:
        patterns:
          - "actions/*"
          - "github/*"
    schedule:
      interval: "weekly"
