name: _lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-linters:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Super-Linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ".github/linters"
          MARKDOWN_CONFIG_FILE: ".markdownlint.yml"
          YAML_CONFIG_FILE: ".yamllint.yml"
          VALIDATE_ALL_CODEBASE: false
          MULTI_STATUS: false
          VALIDATE_BIOME_FORMAT: false # TODO(lint): Consider enabling Biome formatting after testing
