name: clean-owners

on:
  # Scheduled trigger
  schedule:
    # Run weekly on Saturdays
    - cron: "30 1 * * 6"
  # Manual trigger
  workflow_dispatch:

permissions:
  issues: none

jobs:
  clean-owners:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 🧼 clean codeowners
        uses: github/cleanowners@45f292ce59392482f81f03e5ef3c27daaf06183e # v2.1.13
        env:
          GH_TOKEN: ${{ secrets.BLOOMBERG_OSS_USER_TOKEN_READ }}
          ORGANIZATION: bloomberg
          EXEMPT_REPOS: "bloomberg/.github, bloomberg/.allstar"
          DRY_RUN: true
