name: clean-owners

on:
  # Scheduled trigger
  schedule:
    # Run weekly on Saturdays
    - cron: "30 1 * * 6"
  # Manual trigger
  workflow_dispatch:

permissions:
  issues: none

jobs:
  clean-owners:
    runs-on: ubuntu-latest
    permissions:
        issues: write
    steps:
      - name: 🧼 clean codeowners
        uses: github/cleanowners@012102f0cfe38781948400f15f4c03747b0247bc # v1.2.12
        env:
          GH_TOKEN: ${{ secrets.BLOOMBERG_OSS_USER_TOKEN_READ }}
          ORGANIZATION: bloomberg
          EXEMPT_REPOS: "bloomberg/.github, bloomberg/.allstar"
          DRY_RUN: true
