name: clean-owners

on:
  # Scheduled trigger
  schedule:
    # Run weekly on Saturdays
    - cron: "30 1 * * 6"
  # Manual trigger
  workflow_dispatch:

permissions:
  issues: none

jobs:
  clean-owners:
    runs-on: ubuntu-latest
    permissions:
        issues: write
    steps:
      - name: 🧼 clean codeowners
        uses: github/cleanowners@884a0ebb00d66e20774bd1868f42aee014f8e6c3 # v1.3.0
        env:
          GH_TOKEN: ${{ secrets.BLOOMBERG_OSS_USER_TOKEN_READ }}
          ORGANIZATION: bloomberg
          EXEMPT_REPOS: "bloomberg/.github, bloomberg/.allstar"
          DRY_RUN: true
