name: contributor-report

on:
  # Scheduled trigger
  schedule:
    # Run the first day of the month at 00:00
    - cron: "0 0 1 * *"
  # Manual trigger
  workflow_dispatch:

permissions:
  issues: none

jobs:
  contributor-report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define orgs to report contributor activity
        org:
          [
            "bloomberg",
          ]
    permissions:
        # Required to create contributor report
        issues: write
    steps:
      - name: 📅 calculate date
        shell: bash
        run: |
          # Calculate the first day of the previous month
          START_DATE=$(date -d "last month" +%Y-%m-01)
          # Calculate the last day of the previous month
          END_DATE=$(date -d "$START_DATE +1 month -1 day" +%Y-%m-%d)
          # Set an environment variable with the date range
          echo "START_DATE=$START_DATE" >> "$GITHUB_ENV"
          echo "END_DATE=$END_DATE" >> "$GITHUB_ENV"
      - name: 📰 run contributors action
        uses: github/contributors@69e531b620b7e5b0fad2e9823681607b54db447a # v1.5.11
        env:
          GH_TOKEN: ${{ secrets.BLOOMBERG_OSS_USER_TOKEN_READ }}
          START_DATE: ${{ env.START_DATE }}
          END_DATE: ${{ env.END_DATE }}
          ORGANIZATION: ${{ matrix.org }}
          LINK_TO_PROFILE: "True"
      - name: 📥 create issue
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6.0.0
        with:
          title: "📰 Monthly Contributor Report: ${{ matrix.org }}"
          token: ${{ secrets.BLOOMBERG_OSS_USER_TOKEN_READ }}
          content-filepath: "./contributors.md"
          assignees: ${{ github.actor }}
